export const GETPLACESSAGA = 'GETPLACESSAGA';
export const ADDNEWPLACE = 'ADDNEWPLACE';

export const GET_FIVE_PLACES = 'GET_FIVE_PLACES';

export const GETPLACESREVIEW = 'GETPLACESREVIEWS';
export const ADDPLACESREVIEW = 'ADDPLACESREVIEW';
export const ADDPLACERATING = 'ADDPLACERATING';
