export const GETPLACESSAGA = 'GETPLACESSAGA';
export const ADDNEWPLACE = 'ADDNEWPLACE';

export const GET_FIVE_PLACES = 'GET_FIVE_PLACES';
export const CHECKPLACE = 'CHECKPLACE ';

export const GETPLACESREVIEW = 'GETPLACESREVIEWS';
export const ADDPLACESREVIEW = 'ADDPLACESREVIEW';

export const SHARE_PLACE_SAGA = 'SHARE_PLACE';
export const ADDPLACERATING = 'ADDPLACERATING';

